name: GRnnData
description: |
  An onverload of anndata to more easily work with gene networks.
  Allows easy conversion between anndata and grnndata and provide loads of usefull utilities functions.
project_home: https://github.com/cantinilab/GRnnData
documentation_home: https://jkobject.com/GRnnData
publications:
  - 10.1101/2024.07.29.605556
install:
  pypi: grnndata
tags:
  - single cell
  - RNAseq
  - gene networks
  - format
  - utilities
license: MIT
version: v1.0.0
authors:
  - jkobject (jeremie kalfon)
test_command: pip install . && make test
